### PR TITLE
Use OPA v0.49.2

### PR DESCRIPTION
**Pull request by anderseknert**
Do we need something to enable dependabot, or has it just been slow to notice?

### CODE REVIEW

**Comment by srenatus** [comment]
No dependabot setup yet

**Comment by anderseknert** [comment]
OK. I got dependabot suggestions in another repo where I don't think I did anything to set that up, so I figured it would be enabled by default... maybe it's a recent change 🤔

**Comment by srenatus** [comment]
I think some "vulnerable dependencies" are handled differently, without enabling it.

**Comment by anderseknert** [comment]
That makes sense, although I think the OPA update would be included in that category. So it was probably just dependabot being slow after all :)

**Pull request merged**
